from app.session import get_session, add_to_history, accept_disclaimer
from app.intent import classify_intent
from app.apis import (
    search_datasets, get_cdo_details, get_dataset_cdo,
    submit_portal_feedback, contact_cdo_or_dataset_feedback,
)
from app.rag import answer, get_known_topics

DISCLAIMER_TEXT = """
================================================================
  IMPORTANT NOTICE - Please Read Before Proceeding
================================================================

I am an AI-powered assistant for the Government Open Data Portal.

Please be aware:
  * My answers are generated by an AI system and may occasionally
    be incorrect or incomplete.
  * I can only answer questions based on the documents I have
    been provided.
  * I am not a substitute for official government advice or
    legal guidance.
  * My knowledge is limited to topics in this portal's
    documentation.
  * Do not share sensitive personal information in this chat.

By continuing, you acknowledge and accept these limitations.

Type "I agree" to proceed, or "exit" to quit.
================================================================"""

DISCLAIMER_REQUIRED = "Please type 'I agree' to accept the terms before we can begin."
AGREEMENT_PHRASES = {"i agree", "agree", "yes", "ok", "okay", "accept", "i accept", "yes i agree"}


def process_message(session_id: str, user_message: str) -> str:
    session = get_session(session_id)
    if not session:
        return "Session not found. Please start a new session."

    user_message = user_message.strip()
    if not user_message:
        return "Please enter a message."

    if not session.disclaimer_accepted:
        if user_message.lower() in AGREEMENT_PHRASES:
            accept_disclaimer(session_id)
            add_to_history(session_id, "user", user_message)
            response = (
                "Thank you for agreeing. How can I help you today? "
                "I can answer questions about the Government Open Data Portal, "
                "help you search for datasets, or connect you with Chief Data Officers."
            )
            add_to_history(session_id, "assistant", response)
            return response
        return DISCLAIMER_REQUIRED

    recent = session.history[-4:] if len(session.history) >= 4 else session.history
    context_str = "\n".join(f"{m['role'].upper()}: {m['content']}" for m in recent)

    intent_result = classify_intent(user_message, context_str)
    intent = intent_result.get("intent", "rag_chat")
    extracted = intent_result.get("extracted", "")

    if intent == "search":
        response = search_datasets(extracted or user_message)
    elif intent == "cdo_details":
        response = get_cdo_details(extracted or user_message)
    elif intent == "dataset_cdo_link":
        response = get_dataset_cdo(extracted or user_message)
    elif intent == "portal_feedback":
        response = submit_portal_feedback(user_message)
    elif intent == "contact_cdo":
        response = contact_cdo_or_dataset_feedback(extracted)
    else:
        known_topics = get_known_topics()
        history_for_rag = [m for m in session.history if m["role"] in ("user", "assistant")]
        response = answer(user_message, history_for_rag, known_topics)

    add_to_history(session_id, "user", user_message)
    add_to_history(session_id, "assistant", response)
    return response


def get_disclaimer() -> str:
    return DISCLAIMER_TEXT
