from app.session import get_session, add_to_history, accept_disclaimer
from app.intent import classify_intent
from app.apis import (
    search_datasets, get_cdo_details, get_dataset_cdo,
    submit_portal_feedback, contact_cdo_or_dataset_feedback,
)
from app.rag import answer, answer_stream, get_known_topics

DISCLAIMER_TEXT = """
================================================================
  data.gov.in Assistant - Important Notice
================================================================

You are interacting with an AI assistant for the Open Government
Data (OGD) Platform India - data.gov.in.

Please note:
  * Responses are generated by an AI system and may be incorrect,
    outdated or incomplete.
  * I can only answer from the portal's published documentation
    (About, Help, FAQ, NDSAP Implementation Guidelines, Terms of
    Use, Miscellaneous Policies, Accessibility Statement).
  * I am not a substitute for the official information on
    data.gov.in or for advice from the concerned Ministry,
    Department or Chief Data Officer.
  * Do not share personal information, login credentials,
    Aadhaar numbers, OTPs or other sensitive data in this chat.
  * For binding information, always verify on data.gov.in or
    contact the NDSAP PMU.

Type "I agree" to proceed, or "exit" to quit.
================================================================"""

DISCLAIMER_REQUIRED = "Please type 'I agree' to accept the terms before we can begin."
AGREEMENT_PHRASES = {"i agree", "agree", "yes", "ok", "okay", "accept", "i accept", "yes i agree"}


_DISCLAIMER_AGREED_GREETING = (
    "Thank you for agreeing. How can I help you today? "
    "I can answer questions about the Government Open Data Portal, "
    "help you search for datasets, or connect you with Chief Data Officers."
)


def _preamble(session, user_message: str) -> str | None:
    """Disclaimer / empty-input handling shared by both message handlers.
    Returns a final reply string if the turn ends here, else None to mean
    'proceed to intent routing'."""
    if not session.disclaimer_accepted:
        if user_message.lower() in AGREEMENT_PHRASES:
            accept_disclaimer(session.session_id)
            add_to_history(session.session_id, "user", user_message)
            add_to_history(session.session_id, "assistant", _DISCLAIMER_AGREED_GREETING)
            return _DISCLAIMER_AGREED_GREETING
        return DISCLAIMER_REQUIRED
    return None


RETRY_PREFIX = "Apologies for the previous reply — let me try that again.\n\n"


def _is_retry(session, intent: str) -> bool:
    """Retry intent only fires when there's an actual previous turn to retry."""
    return intent == "retry" and len(session.history) >= 2


def _route_non_rag(session, user_message: str, intent: str, extracted: str) -> str | None:
    """Resolve non-RAG intents to their canned/API string. Returns None when
    the intent is rag_chat or retry (caller handles RAG)."""
    if intent == "search":
        return search_datasets(extracted or user_message)
    if intent == "cdo_details":
        return get_cdo_details(extracted or user_message)
    if intent == "dataset_cdo_link":
        return get_dataset_cdo(extracted or user_message)
    if intent == "portal_feedback":
        return submit_portal_feedback(user_message)
    if intent == "contact_cdo":
        return contact_cdo_or_dataset_feedback(extracted)
    return None


def _classify(session, user_message: str) -> tuple[str, str]:
    recent = session.history[-4:] if len(session.history) >= 4 else session.history
    context_str = "\n".join(f"{m['role'].upper()}: {m['content']}" for m in recent)
    intent_result = classify_intent(user_message, context_str)
    return intent_result.get("intent", "rag_chat"), intent_result.get("extracted", "")


def process_message(session_id: str, user_message: str) -> str:
    """Non-streaming handler. Returns the full reply as a single string.
    Kept for backwards compatibility with the existing /chat endpoint."""
    session = get_session(session_id)
    if not session:
        return "Session not found. Please start a new session."

    user_message = user_message.strip()
    if not user_message:
        return "Please enter a message."

    preamble = _preamble(session, user_message)
    if preamble is not None:
        return preamble

    intent, extracted = _classify(session, user_message)
    routed = _route_non_rag(session, user_message, intent, extracted)
    if routed is not None:
        response = routed
    elif _is_retry(session, intent):
        clarified = extracted or user_message
        history_for_rag = [m for m in session.history if m["role"] in ("user", "assistant")]
        known_topics = get_known_topics()
        response = RETRY_PREFIX + answer(
            clarified, history_for_rag, known_topics, skip_predefined_qa=True
        )
    else:
        known_topics = get_known_topics()
        history_for_rag = [m for m in session.history if m["role"] in ("user", "assistant")]
        response = answer(user_message, history_for_rag, known_topics)

    add_to_history(session_id, "user", user_message)
    add_to_history(session_id, "assistant", response)
    return response


def process_message_stream(session_id: str, user_message: str):
    """Streaming handler. Yields string chunks as they become available.

    Refusals / template / API responses are emitted as a single chunk.
    The grounded RAG answer streams token-by-token from Ollama. The full
    accumulated response is written to history at the end of the turn."""
    session = get_session(session_id)
    if not session:
        yield "Session not found. Please start a new session."
        return

    user_message = user_message.strip()
    if not user_message:
        yield "Please enter a message."
        return

    preamble = _preamble(session, user_message)
    if preamble is not None:
        yield preamble
        return

    intent, extracted = _classify(session, user_message)
    routed = _route_non_rag(session, user_message, intent, extracted)
    if routed is not None:
        add_to_history(session_id, "user", user_message)
        add_to_history(session_id, "assistant", routed)
        yield routed
        return

    known_topics = get_known_topics()
    history_for_rag = [m for m in session.history if m["role"] in ("user", "assistant")]

    if _is_retry(session, intent):
        clarified = extracted or user_message
        yield RETRY_PREFIX
        chunks: list[str] = [RETRY_PREFIX]
        for chunk in answer_stream(
            clarified, history_for_rag, known_topics, skip_predefined_qa=True
        ):
            chunks.append(chunk)
            yield chunk
    else:
        chunks = []
        for chunk in answer_stream(user_message, history_for_rag, known_topics):
            chunks.append(chunk)
            yield chunk

    response = "".join(chunks)
    add_to_history(session_id, "user", user_message)
    add_to_history(session_id, "assistant", response)


def get_disclaimer() -> str:
    return DISCLAIMER_TEXT
